// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Settlement extends Building {
	public Settlement() {
        super(1);
    }
}
