// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Building {
	/**
	 * 
	 */
	
	/**
	 * 
	 */
	private int victoryPoints;
	public Building(){
		this.victoryPoints = victoryPoints;
	}

	public int getVictoryPoints(){
		return victoryPoints;
	}

	public void setVictoryPoints(){
		this.victoryPoints = victoryPoints;
	}
}
